artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mflowruns/training/TheBloke/stable-code-3b-GPTQ/2024-01-23
  21:52:56/0
creation_time: 1706046791862
experiment_id: '0'
last_update_time: 1706046791862
lifecycle_stage: active
name: Default
