artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mlflowruns/training/mistralai/Mistral-7B-Instruct-v0.2/2024-01-25
  17:43:46/0
creation_time: 1706204626556
experiment_id: '0'
last_update_time: 1706204626556
lifecycle_stage: active
name: Default
