artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mlflowruns/training/mistralai/Mistral-7B-Instruct-v0.2/2024-01-25
  17:49:00/740096183652441645
creation_time: 1706204941442
experiment_id: '740096183652441645'
last_update_time: 1706204941442
lifecycle_stage: active
name: /Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/LLM Tuning Pipeline
