artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mflowruns/training/TheBloke/stable-code-3b-GPTQ/2024-01-22
  21:24:51/600831885793588611
creation_time: 1705960161552
experiment_id: '600831885793588611'
last_update_time: 1705960161552
lifecycle_stage: active
name: /Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/LLM Tuning Pipeline
