artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mlflowruns/training/mistralai/Mistral-7B-Instruct-v0.2/2024-01-25
  17:21:52/939647838266902271
creation_time: 1706203312800
experiment_id: '939647838266902271'
last_update_time: 1706203312800
lifecycle_stage: active
name: /Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/LLM Tuning Pipeline
