artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mflowruns/training/TheBloke/stable-code-3b-GPTQ/2024-01-22
  21:24:51/0
creation_time: 1705960161208
experiment_id: '0'
last_update_time: 1705960161208
lifecycle_stage: active
name: Default
