artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mlflowruns/training/mistralai/Mistral-7B-Instruct-v0.2/2024-01-25
  17:35:23/949585306688543868
creation_time: 1706204124386
experiment_id: '949585306688543868'
last_update_time: 1706204124386
lifecycle_stage: active
name: /Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/LLM Tuning Pipeline
