artifact_location: /Workspace/Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/mlflowruns/training/mistralai/Mistral-7B-Instruct-v0.2/2024-01-25
  17:43:46/358895969024239512
creation_time: 1706204626946
experiment_id: '358895969024239512'
last_update_time: 1706204626946
lifecycle_stage: active
name: /Repos/nicholas@nousot.com/dbks_hackathon_DBUBurners/LLM Tuning Pipeline
